import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/public/favicon.ico' />
      </Head>
      <h1 className='flex justify-center items-center p-5 text-green-500 text-lg font-bold'>
        This Is The Home Page! Everyone can see it.
      </h1>
    </>
  );
}
